/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedPostRouteImport } from './routes/_authenticated/post'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthenticatedBusinessApplyRouteImport } from './routes/_authenticated/business.apply'
import { Route as AuthenticatedBusinessDashboardRouteImport } from './routes/_authenticated/business.dashboard'
import { Route as AuthenticatedBusinessPaymentsRouteImport } from './routes/_authenticated/business.payments'
import { Route as AuthenticatedBusinessPendingRouteImport } from './routes/_authenticated/business.pending'
import { Route as AuthenticatedBusinessProfileRouteImport } from './routes/_authenticated/business.profile'
import { Route as AuthenticatedBusinessPromotionsRouteImport } from './routes/_authenticated/business.promotions'
import { Route as AuthenticatedBusinessPromotionsNewRouteImport } from './routes/_authenticated/business.promotions.new'
import { Route as AuthenticatedEditKindIdRouteImport } from './routes/_authenticated/edit.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostRoute = AuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBusinessApplyRoute =
  AuthenticatedBusinessApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessDashboardRoute =
  AuthenticatedBusinessDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessPaymentsRoute =
  AuthenticatedBusinessPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessPendingRoute =
  AuthenticatedBusinessPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessProfileRoute =
  AuthenticatedBusinessProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessPromotionsRoute =
  AuthenticatedBusinessPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessPromotionsNewRoute =
  AuthenticatedBusinessPromotionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBusinessPromotionsRoute,
  } as any)
const AuthenticatedEditKindIdRoute = AuthenticatedEditKindIdRouteImport.update({
  id: '/edit/$kind/$id',
  path: '/edit/$kind/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business': typeof AuthenticatedBusinessRouteWithChildren
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store/$slug': typeof StoreSlugRoute
  '/business/apply': typeof AuthenticatedBusinessApplyRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/payments': typeof AuthenticatedBusinessPaymentsRoute
  '/business/pending': typeof AuthenticatedBusinessPendingRoute
  '/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/business/promotions': typeof AuthenticatedBusinessPromotionsRouteWithChildren
  '/business/promotions/new': typeof AuthenticatedBusinessPromotionsNewRoute
  '/edit/$kind/$id': typeof AuthenticatedEditKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business': typeof AuthenticatedBusinessRouteWithChildren
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store/$slug': typeof StoreSlugRoute
  '/business/apply': typeof AuthenticatedBusinessApplyRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/payments': typeof AuthenticatedBusinessPaymentsRoute
  '/business/pending': typeof AuthenticatedBusinessPendingRoute
  '/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/business/promotions': typeof AuthenticatedBusinessPromotionsRouteWithChildren
  '/business/promotions/new': typeof AuthenticatedBusinessPromotionsNewRoute
  '/edit/$kind/$id': typeof AuthenticatedEditKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRouteWithChildren
  '/_authenticated/post': typeof AuthenticatedPostRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/store/$slug': typeof StoreSlugRoute
  '/_authenticated/business/apply': typeof AuthenticatedBusinessApplyRoute
  '/_authenticated/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/_authenticated/business/payments': typeof AuthenticatedBusinessPaymentsRoute
  '/_authenticated/business/pending': typeof AuthenticatedBusinessPendingRoute
  '/_authenticated/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/_authenticated/business/promotions': typeof AuthenticatedBusinessPromotionsRouteWithChildren
  '/_authenticated/business/promotions/new': typeof AuthenticatedBusinessPromotionsNewRoute
  '/_authenticated/edit/$kind/$id': typeof AuthenticatedEditKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/business'
    | '/post'
    | '/profile'
    | '/store/$slug'
    | '/business/apply'
    | '/business/dashboard'
    | '/business/payments'
    | '/business/pending'
    | '/business/profile'
    | '/business/promotions'
    | '/business/promotions/new'
    | '/edit/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/business'
    | '/post'
    | '/profile'
    | '/store/$slug'
    | '/business/apply'
    | '/business/dashboard'
    | '/business/payments'
    | '/business/pending'
    | '/business/profile'
    | '/business/promotions'
    | '/business/promotions/new'
    | '/edit/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/business'
    | '/_authenticated/post'
    | '/_authenticated/profile'
    | '/store/$slug'
    | '/_authenticated/business/apply'
    | '/_authenticated/business/dashboard'
    | '/_authenticated/business/payments'
    | '/_authenticated/business/pending'
    | '/_authenticated/business/profile'
    | '/_authenticated/business/promotions'
    | '/_authenticated/business/promotions/new'
    | '/_authenticated/edit/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post': {
      id: '/_authenticated/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business/apply': {
      id: '/_authenticated/business/apply'
      path: '/apply'
      fullPath: '/business/apply'
      preLoaderRoute: typeof AuthenticatedBusinessApplyRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/dashboard': {
      id: '/_authenticated/business/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/payments': {
      id: '/_authenticated/business/payments'
      path: '/payments'
      fullPath: '/business/payments'
      preLoaderRoute: typeof AuthenticatedBusinessPaymentsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/pending': {
      id: '/_authenticated/business/pending'
      path: '/pending'
      fullPath: '/business/pending'
      preLoaderRoute: typeof AuthenticatedBusinessPendingRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/profile': {
      id: '/_authenticated/business/profile'
      path: '/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof AuthenticatedBusinessProfileRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/promotions': {
      id: '/_authenticated/business/promotions'
      path: '/promotions'
      fullPath: '/business/promotions'
      preLoaderRoute: typeof AuthenticatedBusinessPromotionsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/promotions/new': {
      id: '/_authenticated/business/promotions/new'
      path: '/new'
      fullPath: '/business/promotions/new'
      preLoaderRoute: typeof AuthenticatedBusinessPromotionsNewRouteImport
      parentRoute: typeof AuthenticatedBusinessPromotionsRoute
    }
    '/_authenticated/edit/$kind/$id': {
      id: '/_authenticated/edit/$kind/$id'
      path: '/edit/$kind/$id'
      fullPath: '/edit/$kind/$id'
      preLoaderRoute: typeof AuthenticatedEditKindIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedBusinessPromotionsRouteChildren {
  AuthenticatedBusinessPromotionsNewRoute: typeof AuthenticatedBusinessPromotionsNewRoute
}

const AuthenticatedBusinessPromotionsRouteChildren: AuthenticatedBusinessPromotionsRouteChildren =
  {
    AuthenticatedBusinessPromotionsNewRoute:
      AuthenticatedBusinessPromotionsNewRoute,
  }

const AuthenticatedBusinessPromotionsRouteWithChildren =
  AuthenticatedBusinessPromotionsRoute._addFileChildren(
    AuthenticatedBusinessPromotionsRouteChildren,
  )

interface AuthenticatedBusinessRouteChildren {
  AuthenticatedBusinessApplyRoute: typeof AuthenticatedBusinessApplyRoute
  AuthenticatedBusinessDashboardRoute: typeof AuthenticatedBusinessDashboardRoute
  AuthenticatedBusinessPaymentsRoute: typeof AuthenticatedBusinessPaymentsRoute
  AuthenticatedBusinessPendingRoute: typeof AuthenticatedBusinessPendingRoute
  AuthenticatedBusinessProfileRoute: typeof AuthenticatedBusinessProfileRoute
  AuthenticatedBusinessPromotionsRoute: typeof AuthenticatedBusinessPromotionsRouteWithChildren
}

const AuthenticatedBusinessRouteChildren: AuthenticatedBusinessRouteChildren = {
  AuthenticatedBusinessApplyRoute: AuthenticatedBusinessApplyRoute,
  AuthenticatedBusinessDashboardRoute: AuthenticatedBusinessDashboardRoute,
  AuthenticatedBusinessPaymentsRoute: AuthenticatedBusinessPaymentsRoute,
  AuthenticatedBusinessPendingRoute: AuthenticatedBusinessPendingRoute,
  AuthenticatedBusinessProfileRoute: AuthenticatedBusinessProfileRoute,
  AuthenticatedBusinessPromotionsRoute:
    AuthenticatedBusinessPromotionsRouteWithChildren,
}

const AuthenticatedBusinessRouteWithChildren =
  AuthenticatedBusinessRoute._addFileChildren(
    AuthenticatedBusinessRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRouteWithChildren
  AuthenticatedPostRoute: typeof AuthenticatedPostRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedEditKindIdRoute: typeof AuthenticatedEditKindIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRouteWithChildren,
  AuthenticatedPostRoute: AuthenticatedPostRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedEditKindIdRoute: AuthenticatedEditKindIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
